[package]
name = "rust-client"
version = "0.1.0"
edition = "2021"

[dependencies]
capnp = "0.19"
capnp-rpc = "0.19"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["compat"] }

[build-dependencies]
capnpc = "0.19"
walkdir = "2.3.2"
